name: escuela_timbres
description: App Android para gestionar timbres escolares con ESP8266 en red local.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <5.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.14
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/manager_bell_icon.png
    - assets/splash/splash.png

flutter_launcher_icons:
  image_path: "assets/icons/manager_bell_icon.png"
  android:
    generate: true
  windows:
    generate: true
    image_path: "assets/icons/manager_bell_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  image: assets/splash/splash.png
  color: "#FFFFFF"
  android: true
  ios: false
  android_gravity: center
